### ISSUE TITLE
Incorrect L1 RPC chain

### ISSUE THREAD

**Issue by InfiniteLoop889** [conduitxyz/node#4]
Hello

I tried to set up a testnet node for Zora Sepolia with the RPC "https://sepolia.rpc.zora.energy/" and after running `docker compose up --build` i keep getting the following errors:

node-node-1  | t=2023-11-21T20:11:14+0000 lvl=eror msg="Error initializing the rollup node" err="failed to init L1: failed to validate the L1 config: incorrect L1 RPC chain id 999999999, expected 11155111"
node-node-1  | t=2023-11-21T20:11:14+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node: failed to init L1: failed to validate the L1 config: incorrect L1 RPC chain id 999999999, expected 11155111"

Could you tell me which RPC I should use? I couldn't find one with the chain ID 11155111.

**Comment by kahuang** [comment]
You need the base sepolia l1 rpc, here's a list: https://chainlist.org/chain/11155111

The sepolia.rpc.zora.energy url is for the rollup itself
